# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/common/metadata.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'protos/common/metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprotos/common/metadata.proto\x12\x0cgenai.common\"\x97\x01\n\x08Metadata\x12\x1d\n\nrequest_id\x18\x01 \x01(\tR\trequestId\x12\x17\n\x07user_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n\nsession_id\x18\x03 \x01(\tR\tsessionId\x12\x1c\n\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x16\n\x06source\x18\x05 \x01(\tR\x06source\"I\n\x0f\x43onfidenceScore\x12\x14\n\x05score\x18\x01 \x01(\x01R\x05score\x12 \n\x0b\x65xplanation\x18\x02 \x01(\tR\x0b\x65xplanationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.common.metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METADATA']._serialized_start=47
  _globals['_METADATA']._serialized_end=198
  _globals['_CONFIDENCESCORE']._serialized_start=200
  _globals['_CONFIDENCESCORE']._serialized_end=273
# @@protoc_insertion_point(module_scope)
