# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/common/pagination.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'protos/common/pagination.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eprotos/common/pagination.proto\x12\x0cgenai.common\"D\n\x11PaginationRequest\x12\x12\n\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n\tpage_size\x18\x02 \x01(\x05R\x08pageSize\"\xc5\x01\n\x12PaginationResponse\x12\x1f\n\x0btotal_count\x18\x01 \x01(\x05R\ntotalCount\x12\x12\n\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n\tpage_size\x18\x03 \x01(\x05R\x08pageSize\x12\x1f\n\x0btotal_pages\x18\x04 \x01(\x05R\ntotalPages\x12\x19\n\x08has_next\x18\x05 \x01(\x08R\x07hasNext\x12!\n\x0chas_previous\x18\x06 \x01(\x08R\x0bhasPrevious\"B\n\nSortOption\x12\x14\n\x05\x66ield\x18\x01 \x01(\tR\x05\x66ield\x12\x1e\n\ndescending\x18\x02 \x01(\x08R\ndescendingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.common.pagination_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAGINATIONREQUEST']._serialized_start=48
  _globals['_PAGINATIONREQUEST']._serialized_end=116
  _globals['_PAGINATIONRESPONSE']._serialized_start=119
  _globals['_PAGINATIONRESPONSE']._serialized_end=316
  _globals['_SORTOPTION']._serialized_start=318
  _globals['_SORTOPTION']._serialized_end=384
# @@protoc_insertion_point(module_scope)
