# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from mysingle.protos.services.genai.v1 import (
    chatops_pb2 as protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2,
)


class ChatOpsServiceStub(object):
    """ChatOps 서비스
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/genai.chatops.ChatOpsService/CreateSession',
                request_serializer=protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.ChatStream = channel.stream_stream(
                '/genai.chatops.ChatOpsService/ChatStream',
                request_serializer=protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.ChatMessage.SerializeToString,
                response_deserializer=protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.GetSessionHistory = channel.unary_unary(
                '/genai.chatops.ChatOpsService/GetSessionHistory',
                request_serializer=protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.GetSessionHistoryRequest.SerializeToString,
                response_deserializer=protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.GetSessionHistoryResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/genai.chatops.ChatOpsService/CloseSession',
                request_serializer=protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.CloseSessionResponse.FromString,
                _registered_method=True)


class ChatOpsServiceServicer(object):
    """ChatOps 서비스
    """

    def CreateSession(self, request, context):
        """세션 생성
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStream(self, request_iterator, context):
        """양방향 스트리밍 대화
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionHistory(self, request, context):
        """세션 히스토리 조회
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """세션 종료
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatOpsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.CreateSessionRequest.FromString,
                    response_serializer=protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.CreateSessionResponse.SerializeToString,
            ),
            'ChatStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.ChatMessage.FromString,
                    response_serializer=protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.ChatResponse.SerializeToString,
            ),
            'GetSessionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionHistory,
                    request_deserializer=protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.GetSessionHistoryRequest.FromString,
                    response_serializer=protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.GetSessionHistoryResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.CloseSessionRequest.FromString,
                    response_serializer=protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.CloseSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'genai.chatops.ChatOpsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('genai.chatops.ChatOpsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatOpsService(object):
    """ChatOps 서비스
    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genai.chatops.ChatOpsService/CreateSession',
            protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.CreateSessionRequest.SerializeToString,
            protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/genai.chatops.ChatOpsService/ChatStream',
            protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.ChatMessage.SerializeToString,
            protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genai.chatops.ChatOpsService/GetSessionHistory',
            protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.GetSessionHistoryRequest.SerializeToString,
            protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.GetSessionHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genai.chatops.ChatOpsService/CloseSession',
            protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.CloseSessionRequest.SerializeToString,
            protos_dot_services_dot_genai_dot_v1_dot_chatops__pb2.CloseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
