# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from services.genai.v1 import dsl_validator_pb2 as services_dot_genai_dot_v1_dot_dsl__validator__pb2


class DSLValidatorServiceStub(object):
    """DSL Validator 서비스
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateDSL = channel.unary_unary(
                '/genai.dsl_validator.DSLValidatorService/ValidateDSL',
                request_serializer=services_dot_genai_dot_v1_dot_dsl__validator__pb2.ValidateDSLRequest.SerializeToString,
                response_deserializer=services_dot_genai_dot_v1_dot_dsl__validator__pb2.ValidateDSLResponse.FromString,
                _registered_method=True)
        self.AutocompleteDSL = channel.unary_unary(
                '/genai.dsl_validator.DSLValidatorService/AutocompleteDSL',
                request_serializer=services_dot_genai_dot_v1_dot_dsl__validator__pb2.AutocompleteDSLRequest.SerializeToString,
                response_deserializer=services_dot_genai_dot_v1_dot_dsl__validator__pb2.AutocompleteDSLResponse.FromString,
                _registered_method=True)
        self.GetSyntaxHelp = channel.unary_unary(
                '/genai.dsl_validator.DSLValidatorService/GetSyntaxHelp',
                request_serializer=services_dot_genai_dot_v1_dot_dsl__validator__pb2.GetSyntaxHelpRequest.SerializeToString,
                response_deserializer=services_dot_genai_dot_v1_dot_dsl__validator__pb2.GetSyntaxHelpResponse.FromString,
                _registered_method=True)


class DSLValidatorServiceServicer(object):
    """DSL Validator 서비스
    """

    def ValidateDSL(self, request, context):
        """DSL 코드 검증
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AutocompleteDSL(self, request, context):
        """DSL 자동 완성 제안
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSyntaxHelp(self, request, context):
        """DSL 문법 도움말
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DSLValidatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateDSL': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateDSL,
                    request_deserializer=services_dot_genai_dot_v1_dot_dsl__validator__pb2.ValidateDSLRequest.FromString,
                    response_serializer=services_dot_genai_dot_v1_dot_dsl__validator__pb2.ValidateDSLResponse.SerializeToString,
            ),
            'AutocompleteDSL': grpc.unary_unary_rpc_method_handler(
                    servicer.AutocompleteDSL,
                    request_deserializer=services_dot_genai_dot_v1_dot_dsl__validator__pb2.AutocompleteDSLRequest.FromString,
                    response_serializer=services_dot_genai_dot_v1_dot_dsl__validator__pb2.AutocompleteDSLResponse.SerializeToString,
            ),
            'GetSyntaxHelp': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSyntaxHelp,
                    request_deserializer=services_dot_genai_dot_v1_dot_dsl__validator__pb2.GetSyntaxHelpRequest.FromString,
                    response_serializer=services_dot_genai_dot_v1_dot_dsl__validator__pb2.GetSyntaxHelpResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'genai.dsl_validator.DSLValidatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('genai.dsl_validator.DSLValidatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DSLValidatorService(object):
    """DSL Validator 서비스
    """

    @staticmethod
    def ValidateDSL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genai.dsl_validator.DSLValidatorService/ValidateDSL',
            services_dot_genai_dot_v1_dot_dsl__validator__pb2.ValidateDSLRequest.SerializeToString,
            services_dot_genai_dot_v1_dot_dsl__validator__pb2.ValidateDSLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AutocompleteDSL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genai.dsl_validator.DSLValidatorService/AutocompleteDSL',
            services_dot_genai_dot_v1_dot_dsl__validator__pb2.AutocompleteDSLRequest.SerializeToString,
            services_dot_genai_dot_v1_dot_dsl__validator__pb2.AutocompleteDSLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSyntaxHelp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genai.dsl_validator.DSLValidatorService/GetSyntaxHelp',
            services_dot_genai_dot_v1_dot_dsl__validator__pb2.GetSyntaxHelpRequest.SerializeToString,
            services_dot_genai_dot_v1_dot_dsl__validator__pb2.GetSyntaxHelpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
