# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from mysingle.protos.services.genai.v1 import (
    ir_converter_pb2 as protos_dot_services_dot_genai_dot_v1_dot_ir__converter__pb2,
)


class IRConverterServiceStub(object):
    """IR Converter 서비스
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PreviewConversion = channel.unary_unary(
                '/genai.ir_converter.IRConverterService/PreviewConversion',
                request_serializer=protos_dot_services_dot_genai_dot_v1_dot_ir__converter__pb2.PreviewConversionRequest.SerializeToString,
                response_deserializer=protos_dot_services_dot_genai_dot_v1_dot_ir__converter__pb2.PreviewConversionResponse.FromString,
                _registered_method=True)
        self.ExecuteConversion = channel.unary_unary(
                '/genai.ir_converter.IRConverterService/ExecuteConversion',
                request_serializer=protos_dot_services_dot_genai_dot_v1_dot_ir__converter__pb2.ExecuteConversionRequest.SerializeToString,
                response_deserializer=protos_dot_services_dot_genai_dot_v1_dot_ir__converter__pb2.ExecuteConversionResponse.FromString,
                _registered_method=True)
        self.CheckConvertibility = channel.unary_unary(
                '/genai.ir_converter.IRConverterService/CheckConvertibility',
                request_serializer=protos_dot_services_dot_genai_dot_v1_dot_ir__converter__pb2.CheckConvertibilityRequest.SerializeToString,
                response_deserializer=protos_dot_services_dot_genai_dot_v1_dot_ir__converter__pb2.CheckConvertibilityResponse.FromString,
                _registered_method=True)


class IRConverterServiceServicer(object):
    """IR Converter 서비스
    """

    def PreviewConversion(self, request, context):
        """IR 변환 미리보기 (읽기 전용)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteConversion(self, request, context):
        """IR 변환 실행 (Strategy Service 전용)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckConvertibility(self, request, context):
        """변환 가능 여부 확인
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IRConverterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PreviewConversion': grpc.unary_unary_rpc_method_handler(
                    servicer.PreviewConversion,
                    request_deserializer=protos_dot_services_dot_genai_dot_v1_dot_ir__converter__pb2.PreviewConversionRequest.FromString,
                    response_serializer=protos_dot_services_dot_genai_dot_v1_dot_ir__converter__pb2.PreviewConversionResponse.SerializeToString,
            ),
            'ExecuteConversion': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteConversion,
                    request_deserializer=protos_dot_services_dot_genai_dot_v1_dot_ir__converter__pb2.ExecuteConversionRequest.FromString,
                    response_serializer=protos_dot_services_dot_genai_dot_v1_dot_ir__converter__pb2.ExecuteConversionResponse.SerializeToString,
            ),
            'CheckConvertibility': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckConvertibility,
                    request_deserializer=protos_dot_services_dot_genai_dot_v1_dot_ir__converter__pb2.CheckConvertibilityRequest.FromString,
                    response_serializer=protos_dot_services_dot_genai_dot_v1_dot_ir__converter__pb2.CheckConvertibilityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'genai.ir_converter.IRConverterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('genai.ir_converter.IRConverterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IRConverterService(object):
    """IR Converter 서비스
    """

    @staticmethod
    def PreviewConversion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genai.ir_converter.IRConverterService/PreviewConversion',
            protos_dot_services_dot_genai_dot_v1_dot_ir__converter__pb2.PreviewConversionRequest.SerializeToString,
            protos_dot_services_dot_genai_dot_v1_dot_ir__converter__pb2.PreviewConversionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteConversion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genai.ir_converter.IRConverterService/ExecuteConversion',
            protos_dot_services_dot_genai_dot_v1_dot_ir__converter__pb2.ExecuteConversionRequest.SerializeToString,
            protos_dot_services_dot_genai_dot_v1_dot_ir__converter__pb2.ExecuteConversionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckConvertibility(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/genai.ir_converter.IRConverterService/CheckConvertibility',
            protos_dot_services_dot_genai_dot_v1_dot_ir__converter__pb2.CheckConvertibilityRequest.SerializeToString,
            protos_dot_services_dot_genai_dot_v1_dot_ir__converter__pb2.CheckConvertibilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
