# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from mysingle.protos.services.genai.v1 import (
    strategy_builder_pb2 as services_dot_genai_dot_v1_dot_strategy__builder__pb2,
)


class StrategyBuilderServiceStub(object):
    """Strategy Builder 서비스"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateStrategy = channel.unary_unary(
            "/genai.strategy_builder.StrategyBuilderService/GenerateStrategy",
            request_serializer=services_dot_genai_dot_v1_dot_strategy__builder__pb2.GenerateStrategyRequest.SerializeToString,
            response_deserializer=services_dot_genai_dot_v1_dot_strategy__builder__pb2.GenerateStrategyResponse.FromString,
            _registered_method=True,
        )
        self.ValidateProposal = channel.unary_unary(
            "/genai.strategy_builder.StrategyBuilderService/ValidateProposal",
            request_serializer=services_dot_genai_dot_v1_dot_strategy__builder__pb2.ValidateProposalRequest.SerializeToString,
            response_deserializer=services_dot_genai_dot_v1_dot_strategy__builder__pb2.ValidateProposalResponse.FromString,
            _registered_method=True,
        )
        self.CustomizeTemplate = channel.unary_unary(
            "/genai.strategy_builder.StrategyBuilderService/CustomizeTemplate",
            request_serializer=services_dot_genai_dot_v1_dot_strategy__builder__pb2.CustomizeTemplateRequest.SerializeToString,
            response_deserializer=services_dot_genai_dot_v1_dot_strategy__builder__pb2.CustomizeTemplateResponse.FromString,
            _registered_method=True,
        )


class StrategyBuilderServiceServicer(object):
    """Strategy Builder 서비스"""

    def GenerateStrategy(self, request, context):
        """자연어에서 전략 생성"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ValidateProposal(self, request, context):
        """제안서 검증 (STRUCT/STATIC 사전 검증)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CustomizeTemplate(self, request, context):
        """템플릿 기반 전략 커스터마이징"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_StrategyBuilderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GenerateStrategy": grpc.unary_unary_rpc_method_handler(
            servicer.GenerateStrategy,
            request_deserializer=services_dot_genai_dot_v1_dot_strategy__builder__pb2.GenerateStrategyRequest.FromString,
            response_serializer=services_dot_genai_dot_v1_dot_strategy__builder__pb2.GenerateStrategyResponse.SerializeToString,
        ),
        "ValidateProposal": grpc.unary_unary_rpc_method_handler(
            servicer.ValidateProposal,
            request_deserializer=services_dot_genai_dot_v1_dot_strategy__builder__pb2.ValidateProposalRequest.FromString,
            response_serializer=services_dot_genai_dot_v1_dot_strategy__builder__pb2.ValidateProposalResponse.SerializeToString,
        ),
        "CustomizeTemplate": grpc.unary_unary_rpc_method_handler(
            servicer.CustomizeTemplate,
            request_deserializer=services_dot_genai_dot_v1_dot_strategy__builder__pb2.CustomizeTemplateRequest.FromString,
            response_serializer=services_dot_genai_dot_v1_dot_strategy__builder__pb2.CustomizeTemplateResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "genai.strategy_builder.StrategyBuilderService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "genai.strategy_builder.StrategyBuilderService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class StrategyBuilderService(object):
    """Strategy Builder 서비스"""

    @staticmethod
    def GenerateStrategy(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/genai.strategy_builder.StrategyBuilderService/GenerateStrategy",
            services_dot_genai_dot_v1_dot_strategy__builder__pb2.GenerateStrategyRequest.SerializeToString,
            services_dot_genai_dot_v1_dot_strategy__builder__pb2.GenerateStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ValidateProposal(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/genai.strategy_builder.StrategyBuilderService/ValidateProposal",
            services_dot_genai_dot_v1_dot_strategy__builder__pb2.ValidateProposalRequest.SerializeToString,
            services_dot_genai_dot_v1_dot_strategy__builder__pb2.ValidateProposalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CustomizeTemplate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/genai.strategy_builder.StrategyBuilderService/CustomizeTemplate",
            services_dot_genai_dot_v1_dot_strategy__builder__pb2.CustomizeTemplateRequest.SerializeToString,
            services_dot_genai_dot_v1_dot_strategy__builder__pb2.CustomizeTemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
