# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from mysingle.protos.services.backtest.v1 import (
    backtest_service_pb2 as services_dot_backtest_dot_v1_dot_backtest__service__pb2,
)

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in services/backtest/v1/backtest_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class BacktestServiceStub(object):
    """BacktestService service definition for executing and monitoring strategy backtests."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteBacktest = channel.unary_unary(
            "/backtest.BacktestService/ExecuteBacktest",
            request_serializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.ExecuteBacktestRequest.SerializeToString,
            response_deserializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.ExecuteBacktestResponse.FromString,
            _registered_method=True,
        )
        self.GetBacktestResult = channel.unary_unary(
            "/backtest.BacktestService/GetBacktestResult",
            request_serializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.GetBacktestResultRequest.SerializeToString,
            response_deserializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.BacktestResultResponse.FromString,
            _registered_method=True,
        )
        self.StreamBacktestProgress = channel.unary_stream(
            "/backtest.BacktestService/StreamBacktestProgress",
            request_serializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.StreamProgressRequest.SerializeToString,
            response_deserializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.ProgressUpdate.FromString,
            _registered_method=True,
        )
        self.GetBacktestMetrics = channel.unary_unary(
            "/backtest.BacktestService/GetBacktestMetrics",
            request_serializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.GetMetricsRequest.SerializeToString,
            response_deserializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.MetricsResponse.FromString,
            _registered_method=True,
        )
        self.ListBacktests = channel.unary_unary(
            "/backtest.BacktestService/ListBacktests",
            request_serializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.ListBacktestsRequest.SerializeToString,
            response_deserializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.ListBacktestsResponse.FromString,
            _registered_method=True,
        )
        self.CancelBacktest = channel.unary_unary(
            "/backtest.BacktestService/CancelBacktest",
            request_serializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.CancelBacktestRequest.SerializeToString,
            response_deserializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.CancelBacktestResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/backtest.BacktestService/HealthCheck",
            request_serializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )


class BacktestServiceServicer(object):
    """BacktestService service definition for executing and monitoring strategy backtests."""

    def ExecuteBacktest(self, request, context):
        """Execute backtest for a strategy"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetBacktestResult(self, request, context):
        """Get backtest result by ID"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamBacktestProgress(self, request, context):
        """Stream backtest progress updates"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetBacktestMetrics(self, request, context):
        """Get backtest metrics"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListBacktests(self, request, context):
        """List backtests for a user"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CancelBacktest(self, request, context):
        """Cancel a running backtest"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_BacktestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ExecuteBacktest": grpc.unary_unary_rpc_method_handler(
            servicer.ExecuteBacktest,
            request_deserializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.ExecuteBacktestRequest.FromString,
            response_serializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.ExecuteBacktestResponse.SerializeToString,
        ),
        "GetBacktestResult": grpc.unary_unary_rpc_method_handler(
            servicer.GetBacktestResult,
            request_deserializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.GetBacktestResultRequest.FromString,
            response_serializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.BacktestResultResponse.SerializeToString,
        ),
        "StreamBacktestProgress": grpc.unary_stream_rpc_method_handler(
            servicer.StreamBacktestProgress,
            request_deserializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.StreamProgressRequest.FromString,
            response_serializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.ProgressUpdate.SerializeToString,
        ),
        "GetBacktestMetrics": grpc.unary_unary_rpc_method_handler(
            servicer.GetBacktestMetrics,
            request_deserializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.GetMetricsRequest.FromString,
            response_serializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.MetricsResponse.SerializeToString,
        ),
        "ListBacktests": grpc.unary_unary_rpc_method_handler(
            servicer.ListBacktests,
            request_deserializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.ListBacktestsRequest.FromString,
            response_serializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.ListBacktestsResponse.SerializeToString,
        ),
        "CancelBacktest": grpc.unary_unary_rpc_method_handler(
            servicer.CancelBacktest,
            request_deserializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.CancelBacktestRequest.FromString,
            response_serializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.CancelBacktestResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.HealthCheckRequest.FromString,
            response_serializer=services_dot_backtest_dot_v1_dot_backtest__service__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "backtest.BacktestService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "backtest.BacktestService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class BacktestService(object):
    """BacktestService service definition for executing and monitoring strategy backtests."""

    @staticmethod
    def ExecuteBacktest(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/backtest.BacktestService/ExecuteBacktest",
            services_dot_backtest_dot_v1_dot_backtest__service__pb2.ExecuteBacktestRequest.SerializeToString,
            services_dot_backtest_dot_v1_dot_backtest__service__pb2.ExecuteBacktestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetBacktestResult(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/backtest.BacktestService/GetBacktestResult",
            services_dot_backtest_dot_v1_dot_backtest__service__pb2.GetBacktestResultRequest.SerializeToString,
            services_dot_backtest_dot_v1_dot_backtest__service__pb2.BacktestResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamBacktestProgress(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/backtest.BacktestService/StreamBacktestProgress",
            services_dot_backtest_dot_v1_dot_backtest__service__pb2.StreamProgressRequest.SerializeToString,
            services_dot_backtest_dot_v1_dot_backtest__service__pb2.ProgressUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetBacktestMetrics(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/backtest.BacktestService/GetBacktestMetrics",
            services_dot_backtest_dot_v1_dot_backtest__service__pb2.GetMetricsRequest.SerializeToString,
            services_dot_backtest_dot_v1_dot_backtest__service__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListBacktests(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/backtest.BacktestService/ListBacktests",
            services_dot_backtest_dot_v1_dot_backtest__service__pb2.ListBacktestsRequest.SerializeToString,
            services_dot_backtest_dot_v1_dot_backtest__service__pb2.ListBacktestsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CancelBacktest(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/backtest.BacktestService/CancelBacktest",
            services_dot_backtest_dot_v1_dot_backtest__service__pb2.CancelBacktestRequest.SerializeToString,
            services_dot_backtest_dot_v1_dot_backtest__service__pb2.CancelBacktestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/backtest.BacktestService/HealthCheck",
            services_dot_backtest_dot_v1_dot_backtest__service__pb2.HealthCheckRequest.SerializeToString,
            services_dot_backtest_dot_v1_dot_backtest__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
