# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from mysingle.protos.services.strategy.v1 import (
    strategy_service_pb2 as services_dot_strategy_dot_v1_dot_strategy__service__pb2,
)


class StrategyServiceStub(object):
    """Strategy Service - gRPC API
    Used by Backtest Service and GenAI Service for high-performance strategy operations
    StrategyService service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStrategyVersion = channel.unary_unary(
            "/strategy.v1.StrategyService/GetStrategyVersion",
            request_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.GetStrategyVersionRequest.SerializeToString,
            response_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.StrategyVersionResponse.FromString,
            _registered_method=True,
        )
        self.BatchGetStrategyVersions = channel.unary_stream(
            "/strategy.v1.StrategyService/BatchGetStrategyVersions",
            request_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.BatchGetStrategyVersionsRequest.SerializeToString,
            response_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.StrategyVersionResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/strategy.v1.StrategyService/HealthCheck",
            request_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )
        self.ValidateStrategyIR = channel.unary_unary(
            "/strategy.v1.StrategyService/ValidateStrategyIR",
            request_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.ValidateIRRequest.SerializeToString,
            response_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.ValidationResponse.FromString,
            _registered_method=True,
        )
        self.GetStrategyTemplate = channel.unary_unary(
            "/strategy.v1.StrategyService/GetStrategyTemplate",
            request_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.GetTemplateRequest.SerializeToString,
            response_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.TemplateResponse.FromString,
            _registered_method=True,
        )
        self.ListStrategyTemplates = channel.unary_stream(
            "/strategy.v1.StrategyService/ListStrategyTemplates",
            request_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.ListTemplatesRequest.SerializeToString,
            response_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.TemplateResponse.FromString,
            _registered_method=True,
        )
        self.BatchGetStrategies = channel.unary_stream(
            "/strategy.v1.StrategyService/BatchGetStrategies",
            request_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.BatchGetStrategiesRequest.SerializeToString,
            response_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.StrategyResponse.FromString,
            _registered_method=True,
        )
        self.ListUserStrategies = channel.unary_stream(
            "/strategy.v1.StrategyService/ListUserStrategies",
            request_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.ListUserStrategiesRequest.SerializeToString,
            response_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.StrategyResponse.FromString,
            _registered_method=True,
        )
        self.ArchiveStrategy = channel.unary_unary(
            "/strategy.v1.StrategyService/ArchiveStrategy",
            request_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.ArchiveStrategyRequest.SerializeToString,
            response_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.ArchiveStrategyResponse.FromString,
            _registered_method=True,
        )
        self.GetStrategy = channel.unary_unary(
            "/strategy.v1.StrategyService/GetStrategy",
            request_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.GetStrategyRequest.SerializeToString,
            response_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.GetStrategyResponse.FromString,
            _registered_method=True,
        )
        self.ListStrategies = channel.unary_unary(
            "/strategy.v1.StrategyService/ListStrategies",
            request_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.ListStrategiesRequest.SerializeToString,
            response_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.ListStrategiesResponse.FromString,
            _registered_method=True,
        )
        self.ValidateStrategy = channel.unary_unary(
            "/strategy.v1.StrategyService/ValidateStrategy",
            request_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.ValidateStrategyRequest.SerializeToString,
            response_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.ValidateStrategyResponse.FromString,
            _registered_method=True,
        )
        self.GetPortfolioSummary = channel.unary_unary(
            "/strategy.v1.StrategyService/GetPortfolioSummary",
            request_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.GetPortfolioSummaryRequest.SerializeToString,
            response_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.GetPortfolioSummaryResponse.FromString,
            _registered_method=True,
        )


class StrategyServiceServicer(object):
    """Strategy Service - gRPC API
    Used by Backtest Service and GenAI Service for high-performance strategy operations
    StrategyService service definition.
    """

    def GetStrategyVersion(self, request, context):
        """Get a single strategy version
        GetStrategyVersion RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BatchGetStrategyVersions(self, request, context):
        """Batch get multiple strategy versions (streaming response)
        BatchGetStrategyVersions RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check
        HealthCheck RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ValidateStrategyIR(self, request, context):
        """--- New RPCs for GenAI Service ---

        Validate StrategyIR across multiple stages
        ValidateStrategyIR RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetStrategyTemplate(self, request, context):
        """Get a single strategy template
        GetStrategyTemplate RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListStrategyTemplates(self, request, context):
        """List all accessible templates (streaming)
        ListStrategyTemplates RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BatchGetStrategies(self, request, context):
        """Batch get multiple strategies (streaming)
        BatchGetStrategies RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListUserStrategies(self, request, context):
        """List user's strategies (auto-discovery by user_id) - NEW
        ListUserStrategies RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ArchiveStrategy(self, request, context):
        """Archive a strategy (soft delete)
        ArchiveStrategy RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetStrategy(self, request, context):
        """---- ml-service compatibility RPCs ----
        These RPCs are required by `ml-service` and added for backward/forward compatibility.
        GetStrategy RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListStrategies(self, request, context):
        """ListStrategies RPC."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ValidateStrategy(self, request, context):
        """ValidateStrategy RPC."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPortfolioSummary(self, request, context):
        """GetPortfolioSummary RPC."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_StrategyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetStrategyVersion": grpc.unary_unary_rpc_method_handler(
            servicer.GetStrategyVersion,
            request_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.GetStrategyVersionRequest.FromString,
            response_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.StrategyVersionResponse.SerializeToString,
        ),
        "BatchGetStrategyVersions": grpc.unary_stream_rpc_method_handler(
            servicer.BatchGetStrategyVersions,
            request_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.BatchGetStrategyVersionsRequest.FromString,
            response_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.StrategyVersionResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.HealthCheckRequest.FromString,
            response_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.HealthCheckResponse.SerializeToString,
        ),
        "ValidateStrategyIR": grpc.unary_unary_rpc_method_handler(
            servicer.ValidateStrategyIR,
            request_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.ValidateIRRequest.FromString,
            response_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.ValidationResponse.SerializeToString,
        ),
        "GetStrategyTemplate": grpc.unary_unary_rpc_method_handler(
            servicer.GetStrategyTemplate,
            request_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.GetTemplateRequest.FromString,
            response_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.TemplateResponse.SerializeToString,
        ),
        "ListStrategyTemplates": grpc.unary_stream_rpc_method_handler(
            servicer.ListStrategyTemplates,
            request_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.ListTemplatesRequest.FromString,
            response_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.TemplateResponse.SerializeToString,
        ),
        "BatchGetStrategies": grpc.unary_stream_rpc_method_handler(
            servicer.BatchGetStrategies,
            request_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.BatchGetStrategiesRequest.FromString,
            response_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.StrategyResponse.SerializeToString,
        ),
        "ListUserStrategies": grpc.unary_stream_rpc_method_handler(
            servicer.ListUserStrategies,
            request_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.ListUserStrategiesRequest.FromString,
            response_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.StrategyResponse.SerializeToString,
        ),
        "ArchiveStrategy": grpc.unary_unary_rpc_method_handler(
            servicer.ArchiveStrategy,
            request_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.ArchiveStrategyRequest.FromString,
            response_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.ArchiveStrategyResponse.SerializeToString,
        ),
        "GetStrategy": grpc.unary_unary_rpc_method_handler(
            servicer.GetStrategy,
            request_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.GetStrategyRequest.FromString,
            response_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.GetStrategyResponse.SerializeToString,
        ),
        "ListStrategies": grpc.unary_unary_rpc_method_handler(
            servicer.ListStrategies,
            request_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.ListStrategiesRequest.FromString,
            response_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.ListStrategiesResponse.SerializeToString,
        ),
        "ValidateStrategy": grpc.unary_unary_rpc_method_handler(
            servicer.ValidateStrategy,
            request_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.ValidateStrategyRequest.FromString,
            response_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.ValidateStrategyResponse.SerializeToString,
        ),
        "GetPortfolioSummary": grpc.unary_unary_rpc_method_handler(
            servicer.GetPortfolioSummary,
            request_deserializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.GetPortfolioSummaryRequest.FromString,
            response_serializer=services_dot_strategy_dot_v1_dot_strategy__service__pb2.GetPortfolioSummaryResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "strategy.v1.StrategyService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "strategy.v1.StrategyService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class StrategyService(object):
    """Strategy Service - gRPC API
    Used by Backtest Service and GenAI Service for high-performance strategy operations
    StrategyService service definition.
    """

    @staticmethod
    def GetStrategyVersion(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/strategy.v1.StrategyService/GetStrategyVersion",
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.GetStrategyVersionRequest.SerializeToString,
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.StrategyVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def BatchGetStrategyVersions(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/strategy.v1.StrategyService/BatchGetStrategyVersions",
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.BatchGetStrategyVersionsRequest.SerializeToString,
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.StrategyVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/strategy.v1.StrategyService/HealthCheck",
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.HealthCheckRequest.SerializeToString,
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ValidateStrategyIR(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/strategy.v1.StrategyService/ValidateStrategyIR",
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.ValidateIRRequest.SerializeToString,
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.ValidationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetStrategyTemplate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/strategy.v1.StrategyService/GetStrategyTemplate",
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.GetTemplateRequest.SerializeToString,
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.TemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListStrategyTemplates(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/strategy.v1.StrategyService/ListStrategyTemplates",
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.ListTemplatesRequest.SerializeToString,
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.TemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def BatchGetStrategies(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/strategy.v1.StrategyService/BatchGetStrategies",
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.BatchGetStrategiesRequest.SerializeToString,
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.StrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListUserStrategies(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/strategy.v1.StrategyService/ListUserStrategies",
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.ListUserStrategiesRequest.SerializeToString,
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.StrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ArchiveStrategy(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/strategy.v1.StrategyService/ArchiveStrategy",
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.ArchiveStrategyRequest.SerializeToString,
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.ArchiveStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetStrategy(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/strategy.v1.StrategyService/GetStrategy",
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.GetStrategyRequest.SerializeToString,
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.GetStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListStrategies(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/strategy.v1.StrategyService/ListStrategies",
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.ListStrategiesRequest.SerializeToString,
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.ListStrategiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ValidateStrategy(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/strategy.v1.StrategyService/ValidateStrategy",
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.ValidateStrategyRequest.SerializeToString,
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.ValidateStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetPortfolioSummary(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/strategy.v1.StrategyService/GetPortfolioSummary",
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.GetPortfolioSummaryRequest.SerializeToString,
            services_dot_strategy_dot_v1_dot_strategy__service__pb2.GetPortfolioSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
