# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from mysingle.protos.services.iam.v1 import (
    iam_service_pb2 as services_dot_iam_dot_v1_dot_iam__service__pb2,
)

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in services/iam/v1/iam_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class IAMServiceStub(object):
    """IAM Service - gRPC API
    Identity and Access Management service
    Handles user authentication, authorization, and JWT token management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserInfo = channel.unary_unary(
            "/iam.v1.IAMService/GetUserInfo",
            request_serializer=services_dot_iam_dot_v1_dot_iam__service__pb2.GetUserInfoRequest.SerializeToString,
            response_deserializer=services_dot_iam_dot_v1_dot_iam__service__pb2.GetUserInfoResponse.FromString,
            _registered_method=True,
        )
        self.VerifyUserAccess = channel.unary_unary(
            "/iam.v1.IAMService/VerifyUserAccess",
            request_serializer=services_dot_iam_dot_v1_dot_iam__service__pb2.VerifyUserAccessRequest.SerializeToString,
            response_deserializer=services_dot_iam_dot_v1_dot_iam__service__pb2.VerifyUserAccessResponse.FromString,
            _registered_method=True,
        )
        self.BatchGetUsers = channel.unary_stream(
            "/iam.v1.IAMService/BatchGetUsers",
            request_serializer=services_dot_iam_dot_v1_dot_iam__service__pb2.BatchGetUsersRequest.SerializeToString,
            response_deserializer=services_dot_iam_dot_v1_dot_iam__service__pb2.UserResponse.FromString,
            _registered_method=True,
        )
        self.VerifyToken = channel.unary_unary(
            "/iam.v1.IAMService/VerifyToken",
            request_serializer=services_dot_iam_dot_v1_dot_iam__service__pb2.VerifyTokenRequest.SerializeToString,
            response_deserializer=services_dot_iam_dot_v1_dot_iam__service__pb2.VerifyTokenResponse.FromString,
            _registered_method=True,
        )
        self.RefreshToken = channel.unary_unary(
            "/iam.v1.IAMService/RefreshToken",
            request_serializer=services_dot_iam_dot_v1_dot_iam__service__pb2.RefreshTokenRequest.SerializeToString,
            response_deserializer=services_dot_iam_dot_v1_dot_iam__service__pb2.RefreshTokenResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/iam.v1.IAMService/HealthCheck",
            request_serializer=services_dot_iam_dot_v1_dot_iam__service__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=services_dot_iam_dot_v1_dot_iam__service__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )


class IAMServiceServicer(object):
    """IAM Service - gRPC API
    Identity and Access Management service
    Handles user authentication, authorization, and JWT token management
    """

    def GetUserInfo(self, request, context):
        """Get user information by user ID"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def VerifyUserAccess(self, request, context):
        """Verify user access to a resource"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BatchGetUsers(self, request, context):
        """Batch get multiple users (streaming response)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def VerifyToken(self, request, context):
        """Verify JWT token and return user info"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RefreshToken(self, request, context):
        """Refresh access token using refresh token"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_IAMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetUserInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetUserInfo,
            request_deserializer=services_dot_iam_dot_v1_dot_iam__service__pb2.GetUserInfoRequest.FromString,
            response_serializer=services_dot_iam_dot_v1_dot_iam__service__pb2.GetUserInfoResponse.SerializeToString,
        ),
        "VerifyUserAccess": grpc.unary_unary_rpc_method_handler(
            servicer.VerifyUserAccess,
            request_deserializer=services_dot_iam_dot_v1_dot_iam__service__pb2.VerifyUserAccessRequest.FromString,
            response_serializer=services_dot_iam_dot_v1_dot_iam__service__pb2.VerifyUserAccessResponse.SerializeToString,
        ),
        "BatchGetUsers": grpc.unary_stream_rpc_method_handler(
            servicer.BatchGetUsers,
            request_deserializer=services_dot_iam_dot_v1_dot_iam__service__pb2.BatchGetUsersRequest.FromString,
            response_serializer=services_dot_iam_dot_v1_dot_iam__service__pb2.UserResponse.SerializeToString,
        ),
        "VerifyToken": grpc.unary_unary_rpc_method_handler(
            servicer.VerifyToken,
            request_deserializer=services_dot_iam_dot_v1_dot_iam__service__pb2.VerifyTokenRequest.FromString,
            response_serializer=services_dot_iam_dot_v1_dot_iam__service__pb2.VerifyTokenResponse.SerializeToString,
        ),
        "RefreshToken": grpc.unary_unary_rpc_method_handler(
            servicer.RefreshToken,
            request_deserializer=services_dot_iam_dot_v1_dot_iam__service__pb2.RefreshTokenRequest.FromString,
            response_serializer=services_dot_iam_dot_v1_dot_iam__service__pb2.RefreshTokenResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=services_dot_iam_dot_v1_dot_iam__service__pb2.HealthCheckRequest.FromString,
            response_serializer=services_dot_iam_dot_v1_dot_iam__service__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "iam.v1.IAMService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("iam.v1.IAMService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class IAMService(object):
    """IAM Service - gRPC API
    Identity and Access Management service
    Handles user authentication, authorization, and JWT token management
    """

    @staticmethod
    def GetUserInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/iam.v1.IAMService/GetUserInfo",
            services_dot_iam_dot_v1_dot_iam__service__pb2.GetUserInfoRequest.SerializeToString,
            services_dot_iam_dot_v1_dot_iam__service__pb2.GetUserInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def VerifyUserAccess(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/iam.v1.IAMService/VerifyUserAccess",
            services_dot_iam_dot_v1_dot_iam__service__pb2.VerifyUserAccessRequest.SerializeToString,
            services_dot_iam_dot_v1_dot_iam__service__pb2.VerifyUserAccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def BatchGetUsers(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/iam.v1.IAMService/BatchGetUsers",
            services_dot_iam_dot_v1_dot_iam__service__pb2.BatchGetUsersRequest.SerializeToString,
            services_dot_iam_dot_v1_dot_iam__service__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def VerifyToken(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/iam.v1.IAMService/VerifyToken",
            services_dot_iam_dot_v1_dot_iam__service__pb2.VerifyTokenRequest.SerializeToString,
            services_dot_iam_dot_v1_dot_iam__service__pb2.VerifyTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RefreshToken(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/iam.v1.IAMService/RefreshToken",
            services_dot_iam_dot_v1_dot_iam__service__pb2.RefreshTokenRequest.SerializeToString,
            services_dot_iam_dot_v1_dot_iam__service__pb2.RefreshTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/iam.v1.IAMService/HealthCheck",
            services_dot_iam_dot_v1_dot_iam__service__pb2.HealthCheckRequest.SerializeToString,
            services_dot_iam_dot_v1_dot_iam__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
