# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from mysingle.protos.services.portfolio.v1 import (
    portfolio_service_pb2 as services_dot_portfolio_dot_v1_dot_portfolio__service__pb2,
)

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in services/portfolio/v1/portfolio_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class PortfolioServiceStub(object):
    """Portfolio Service - gRPC API
    Manages portfolio state, positions, and transaction history.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPortfolioSummary = channel.unary_unary(
            "/portfolio.v1.PortfolioService/GetPortfolioSummary",
            request_serializer=services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.GetPortfolioSummaryRequest.SerializeToString,
            response_deserializer=services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.PortfolioSummaryResponse.FromString,
            _registered_method=True,
        )
        self.GetPositions = channel.unary_unary(
            "/portfolio.v1.PortfolioService/GetPositions",
            request_serializer=services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.GetPositionsRequest.SerializeToString,
            response_deserializer=services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.GetPositionsResponse.FromString,
            _registered_method=True,
        )
        self.GetTransactions = channel.unary_unary(
            "/portfolio.v1.PortfolioService/GetTransactions",
            request_serializer=services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.GetTransactionsRequest.SerializeToString,
            response_deserializer=services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.GetTransactionsResponse.FromString,
            _registered_method=True,
        )
        self.CreatePortfolio = channel.unary_unary(
            "/portfolio.v1.PortfolioService/CreatePortfolio",
            request_serializer=services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.CreatePortfolioRequest.SerializeToString,
            response_deserializer=services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.PortfolioResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/portfolio.v1.PortfolioService/HealthCheck",
            request_serializer=services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )


class PortfolioServiceServicer(object):
    """Portfolio Service - gRPC API
    Manages portfolio state, positions, and transaction history.
    """

    def GetPortfolioSummary(self, request, context):
        """Get current portfolio summary"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPositions(self, request, context):
        """Get detailed positions"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTransactions(self, request, context):
        """Get transaction history"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreatePortfolio(self, request, context):
        """Create a new portfolio (e.g. for a new strategy deployment)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PortfolioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetPortfolioSummary": grpc.unary_unary_rpc_method_handler(
            servicer.GetPortfolioSummary,
            request_deserializer=services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.GetPortfolioSummaryRequest.FromString,
            response_serializer=services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.PortfolioSummaryResponse.SerializeToString,
        ),
        "GetPositions": grpc.unary_unary_rpc_method_handler(
            servicer.GetPositions,
            request_deserializer=services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.GetPositionsRequest.FromString,
            response_serializer=services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.GetPositionsResponse.SerializeToString,
        ),
        "GetTransactions": grpc.unary_unary_rpc_method_handler(
            servicer.GetTransactions,
            request_deserializer=services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.GetTransactionsRequest.FromString,
            response_serializer=services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.GetTransactionsResponse.SerializeToString,
        ),
        "CreatePortfolio": grpc.unary_unary_rpc_method_handler(
            servicer.CreatePortfolio,
            request_deserializer=services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.CreatePortfolioRequest.FromString,
            response_serializer=services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.PortfolioResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.HealthCheckRequest.FromString,
            response_serializer=services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "portfolio.v1.PortfolioService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "portfolio.v1.PortfolioService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class PortfolioService(object):
    """Portfolio Service - gRPC API
    Manages portfolio state, positions, and transaction history.
    """

    @staticmethod
    def GetPortfolioSummary(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/portfolio.v1.PortfolioService/GetPortfolioSummary",
            services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.GetPortfolioSummaryRequest.SerializeToString,
            services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.PortfolioSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetPositions(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/portfolio.v1.PortfolioService/GetPositions",
            services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.GetPositionsRequest.SerializeToString,
            services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.GetPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTransactions(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/portfolio.v1.PortfolioService/GetTransactions",
            services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.GetTransactionsRequest.SerializeToString,
            services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.GetTransactionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreatePortfolio(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/portfolio.v1.PortfolioService/CreatePortfolio",
            services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.CreatePortfolioRequest.SerializeToString,
            services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.PortfolioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/portfolio.v1.PortfolioService/HealthCheck",
            services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.HealthCheckRequest.SerializeToString,
            services_dot_portfolio_dot_v1_dot_portfolio__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
