# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from services.indicator.v1 import indicator_service_pb2 as services_dot_indicator_dot_v1_dot_indicator__service__pb2


class IndicatorServiceStub(object):
    """IndicatorService provides metadata about technical indicators
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIndicatorMetadata = channel.unary_unary(
                '/indicator.IndicatorService/GetIndicatorMetadata',
                request_serializer=services_dot_indicator_dot_v1_dot_indicator__service__pb2.GetIndicatorMetadataRequest.SerializeToString,
                response_deserializer=services_dot_indicator_dot_v1_dot_indicator__service__pb2.IndicatorMetadataResponse.FromString,
                _registered_method=True)
        self.BatchGetIndicatorMetadata = channel.unary_unary(
                '/indicator.IndicatorService/BatchGetIndicatorMetadata',
                request_serializer=services_dot_indicator_dot_v1_dot_indicator__service__pb2.BatchGetIndicatorMetadataRequest.SerializeToString,
                response_deserializer=services_dot_indicator_dot_v1_dot_indicator__service__pb2.BatchGetIndicatorMetadataResponse.FromString,
                _registered_method=True)
        self.CalculateIndicator = channel.unary_unary(
                '/indicator.IndicatorService/CalculateIndicator',
                request_serializer=services_dot_indicator_dot_v1_dot_indicator__service__pb2.CalculateIndicatorRequest.SerializeToString,
                response_deserializer=services_dot_indicator_dot_v1_dot_indicator__service__pb2.CalculateIndicatorResponse.FromString,
                _registered_method=True)
        self.BatchCalculateIndicators = channel.unary_unary(
                '/indicator.IndicatorService/BatchCalculateIndicators',
                request_serializer=services_dot_indicator_dot_v1_dot_indicator__service__pb2.BatchCalculateIndicatorsRequest.SerializeToString,
                response_deserializer=services_dot_indicator_dot_v1_dot_indicator__service__pb2.BatchCalculateIndicatorsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/indicator.IndicatorService/HealthCheck',
                request_serializer=services_dot_indicator_dot_v1_dot_indicator__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=services_dot_indicator_dot_v1_dot_indicator__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class IndicatorServiceServicer(object):
    """IndicatorService provides metadata about technical indicators
    """

    def GetIndicatorMetadata(self, request, context):
        """Get metadata for a single indicator
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGetIndicatorMetadata(self, request, context):
        """Get metadata for multiple indicators (batch)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateIndicator(self, request, context):
        """Calculate a single indicator
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchCalculateIndicators(self, request, context):
        """Calculate multiple indicators (batch)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IndicatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIndicatorMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndicatorMetadata,
                    request_deserializer=services_dot_indicator_dot_v1_dot_indicator__service__pb2.GetIndicatorMetadataRequest.FromString,
                    response_serializer=services_dot_indicator_dot_v1_dot_indicator__service__pb2.IndicatorMetadataResponse.SerializeToString,
            ),
            'BatchGetIndicatorMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGetIndicatorMetadata,
                    request_deserializer=services_dot_indicator_dot_v1_dot_indicator__service__pb2.BatchGetIndicatorMetadataRequest.FromString,
                    response_serializer=services_dot_indicator_dot_v1_dot_indicator__service__pb2.BatchGetIndicatorMetadataResponse.SerializeToString,
            ),
            'CalculateIndicator': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateIndicator,
                    request_deserializer=services_dot_indicator_dot_v1_dot_indicator__service__pb2.CalculateIndicatorRequest.FromString,
                    response_serializer=services_dot_indicator_dot_v1_dot_indicator__service__pb2.CalculateIndicatorResponse.SerializeToString,
            ),
            'BatchCalculateIndicators': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchCalculateIndicators,
                    request_deserializer=services_dot_indicator_dot_v1_dot_indicator__service__pb2.BatchCalculateIndicatorsRequest.FromString,
                    response_serializer=services_dot_indicator_dot_v1_dot_indicator__service__pb2.BatchCalculateIndicatorsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=services_dot_indicator_dot_v1_dot_indicator__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=services_dot_indicator_dot_v1_dot_indicator__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'indicator.IndicatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('indicator.IndicatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IndicatorService(object):
    """IndicatorService provides metadata about technical indicators
    """

    @staticmethod
    def GetIndicatorMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/indicator.IndicatorService/GetIndicatorMetadata',
            services_dot_indicator_dot_v1_dot_indicator__service__pb2.GetIndicatorMetadataRequest.SerializeToString,
            services_dot_indicator_dot_v1_dot_indicator__service__pb2.IndicatorMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGetIndicatorMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/indicator.IndicatorService/BatchGetIndicatorMetadata',
            services_dot_indicator_dot_v1_dot_indicator__service__pb2.BatchGetIndicatorMetadataRequest.SerializeToString,
            services_dot_indicator_dot_v1_dot_indicator__service__pb2.BatchGetIndicatorMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateIndicator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/indicator.IndicatorService/CalculateIndicator',
            services_dot_indicator_dot_v1_dot_indicator__service__pb2.CalculateIndicatorRequest.SerializeToString,
            services_dot_indicator_dot_v1_dot_indicator__service__pb2.CalculateIndicatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchCalculateIndicators(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/indicator.IndicatorService/BatchCalculateIndicators',
            services_dot_indicator_dot_v1_dot_indicator__service__pb2.BatchCalculateIndicatorsRequest.SerializeToString,
            services_dot_indicator_dot_v1_dot_indicator__service__pb2.BatchCalculateIndicatorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/indicator.IndicatorService/HealthCheck',
            services_dot_indicator_dot_v1_dot_indicator__service__pb2.HealthCheckRequest.SerializeToString,
            services_dot_indicator_dot_v1_dot_indicator__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
