# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from mysingle.protos.services.ml.v1 import (
    ml_service_pb2 as services_dot_ml_dot_v1_dot_ml__service__pb2,
)


class MLServiceStub(object):
    """ML Service - gRPC API used for ML prediction, walk-forward optimization, and
    feature storage workflows.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OptimizeParameters = channel.unary_stream(
            "/ml.MLService/OptimizeParameters",
            request_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.OptimizeRequest.SerializeToString,
            response_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.OptimizeProgress.FromString,
            _registered_method=True,
        )
        self.AnalyzeWalkForward = channel.unary_unary(
            "/ml.MLService/AnalyzeWalkForward",
            request_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeRequest.SerializeToString,
            response_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeResponse.FromString,
            _registered_method=True,
        )
        self.PredictSignal = channel.unary_unary(
            "/ml.MLService/PredictSignal",
            request_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.MLPredictionRequest.SerializeToString,
            response_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.MLSignalInsight.FromString,
            _registered_method=True,
        )
        self.PredictSignalsBatch = channel.unary_stream(
            "/ml.MLService/PredictSignalsBatch",
            request_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.BatchMLPredictionRequest.SerializeToString,
            response_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.MLSignalInsight.FromString,
            _registered_method=True,
        )
        self.StoreFeatures = channel.unary_unary(
            "/ml.MLService/StoreFeatures",
            request_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.FeatureStoreRequest.SerializeToString,
            response_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.FeatureStoreResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/ml.MLService/HealthCheck",
            request_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )
        self.AnalyzeMLBacktestPerformance = channel.unary_unary(
            "/ml.MLService/AnalyzeMLBacktestPerformance",
            request_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeMLBacktestPerformanceRequest.SerializeToString,
            response_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeMLBacktestPerformanceResponse.FromString,
            _registered_method=True,
        )


class MLServiceServicer(object):
    """ML Service - gRPC API used for ML prediction, walk-forward optimization, and
    feature storage workflows.
    """

    def OptimizeParameters(self, request, context):
        """Walk-forward parameter optimization streaming progress updates to callers."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AnalyzeWalkForward(self, request, context):
        """Run statistical analysis across walk-forward windows."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PredictSignal(self, request, context):
        """Generate a single ML signal prediction."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PredictSignalsBatch(self, request, context):
        """Stream batch ML predictions for multiple feature vectors."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StoreFeatures(self, request, context):
        """Store computed features inside the feature store."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Report service health state."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AnalyzeMLBacktestPerformance(self, request, context):
        """Analyze ML-driven backtest performance submitted by backtest service."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "OptimizeParameters": grpc.unary_stream_rpc_method_handler(
            servicer.OptimizeParameters,
            request_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.OptimizeRequest.FromString,
            response_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.OptimizeProgress.SerializeToString,
        ),
        "AnalyzeWalkForward": grpc.unary_unary_rpc_method_handler(
            servicer.AnalyzeWalkForward,
            request_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeRequest.FromString,
            response_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeResponse.SerializeToString,
        ),
        "PredictSignal": grpc.unary_unary_rpc_method_handler(
            servicer.PredictSignal,
            request_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.MLPredictionRequest.FromString,
            response_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.MLSignalInsight.SerializeToString,
        ),
        "PredictSignalsBatch": grpc.unary_stream_rpc_method_handler(
            servicer.PredictSignalsBatch,
            request_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.BatchMLPredictionRequest.FromString,
            response_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.MLSignalInsight.SerializeToString,
        ),
        "StoreFeatures": grpc.unary_unary_rpc_method_handler(
            servicer.StoreFeatures,
            request_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.FeatureStoreRequest.FromString,
            response_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.FeatureStoreResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.HealthCheckRequest.FromString,
            response_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.HealthCheckResponse.SerializeToString,
        ),
        "AnalyzeMLBacktestPerformance": grpc.unary_unary_rpc_method_handler(
            servicer.AnalyzeMLBacktestPerformance,
            request_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeMLBacktestPerformanceRequest.FromString,
            response_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeMLBacktestPerformanceResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ml.MLService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("ml.MLService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class MLService(object):
    """ML Service - gRPC API used for ML prediction, walk-forward optimization, and
    feature storage workflows.
    """

    @staticmethod
    def OptimizeParameters(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/ml.MLService/OptimizeParameters",
            services_dot_ml_dot_v1_dot_ml__service__pb2.OptimizeRequest.SerializeToString,
            services_dot_ml_dot_v1_dot_ml__service__pb2.OptimizeProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AnalyzeWalkForward(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml.MLService/AnalyzeWalkForward",
            services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeRequest.SerializeToString,
            services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def PredictSignal(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml.MLService/PredictSignal",
            services_dot_ml_dot_v1_dot_ml__service__pb2.MLPredictionRequest.SerializeToString,
            services_dot_ml_dot_v1_dot_ml__service__pb2.MLSignalInsight.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def PredictSignalsBatch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/ml.MLService/PredictSignalsBatch",
            services_dot_ml_dot_v1_dot_ml__service__pb2.BatchMLPredictionRequest.SerializeToString,
            services_dot_ml_dot_v1_dot_ml__service__pb2.MLSignalInsight.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StoreFeatures(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml.MLService/StoreFeatures",
            services_dot_ml_dot_v1_dot_ml__service__pb2.FeatureStoreRequest.SerializeToString,
            services_dot_ml_dot_v1_dot_ml__service__pb2.FeatureStoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml.MLService/HealthCheck",
            services_dot_ml_dot_v1_dot_ml__service__pb2.HealthCheckRequest.SerializeToString,
            services_dot_ml_dot_v1_dot_ml__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AnalyzeMLBacktestPerformance(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml.MLService/AnalyzeMLBacktestPerformance",
            services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeMLBacktestPerformanceRequest.SerializeToString,
            services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeMLBacktestPerformanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
