# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from mysingle.protos.services.ml.v1 import (
    ml_service_pb2 as services_dot_ml_dot_v1_dot_ml__service__pb2,
)

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in services/ml/v1/ml_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MLServiceStub(object):
    """ML Service - gRPC API used for ML prediction, walk-forward optimization, and
    feature storage workflows.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OptimizeParameters = channel.unary_stream(
            "/ml.MLService/OptimizeParameters",
            request_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.OptimizeRequest.SerializeToString,
            response_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.OptimizeProgress.FromString,
            _registered_method=True,
        )
        self.AnalyzeWalkForward = channel.unary_unary(
            "/ml.MLService/AnalyzeWalkForward",
            request_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeRequest.SerializeToString,
            response_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeResponse.FromString,
            _registered_method=True,
        )
        self.PredictSignal = channel.unary_unary(
            "/ml.MLService/PredictSignal",
            request_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.MLPredictionRequest.SerializeToString,
            response_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.MLSignalInsight.FromString,
            _registered_method=True,
        )
        self.PredictSignalsBatch = channel.unary_stream(
            "/ml.MLService/PredictSignalsBatch",
            request_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.BatchMLPredictionRequest.SerializeToString,
            response_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.MLSignalInsight.FromString,
            _registered_method=True,
        )
        self.StoreFeatures = channel.unary_unary(
            "/ml.MLService/StoreFeatures",
            request_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.FeatureStoreRequest.SerializeToString,
            response_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.FeatureStoreResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/ml.MLService/HealthCheck",
            request_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )
        self.AnalyzeMLBacktestPerformance = channel.unary_unary(
            "/ml.MLService/AnalyzeMLBacktestPerformance",
            request_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeMLBacktestPerformanceRequest.SerializeToString,
            response_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeMLBacktestPerformanceResponse.FromString,
            _registered_method=True,
        )
        self.ListModels = channel.unary_unary(
            "/ml.MLService/ListModels",
            request_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.ListModelsRequest.SerializeToString,
            response_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.ListModelsResponse.FromString,
            _registered_method=True,
        )
        self.GetModelInfo = channel.unary_unary(
            "/ml.MLService/GetModelInfo",
            request_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.GetModelInfoRequest.SerializeToString,
            response_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.GetModelInfoResponse.FromString,
            _registered_method=True,
        )
        self.RecommendModel = channel.unary_unary(
            "/ml.MLService/RecommendModel",
            request_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.RecommendModelRequest.SerializeToString,
            response_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.RecommendModelResponse.FromString,
            _registered_method=True,
        )
        self.SuggestParameters = channel.unary_unary(
            "/ml.MLService/SuggestParameters",
            request_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.SuggestParametersRequest.SerializeToString,
            response_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.SuggestParametersResponse.FromString,
            _registered_method=True,
        )
        self.GetMLBacktestPerformance = channel.unary_unary(
            "/ml.MLService/GetMLBacktestPerformance",
            request_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.GetMLBacktestPerformanceRequest.SerializeToString,
            response_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.GetMLBacktestPerformanceResponse.FromString,
            _registered_method=True,
        )
        self.SendDriftNotification = channel.unary_unary(
            "/ml.MLService/SendDriftNotification",
            request_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.DriftNotificationRequest.SerializeToString,
            response_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.DriftNotificationResponse.FromString,
            _registered_method=True,
        )


class MLServiceServicer(object):
    """ML Service - gRPC API used for ML prediction, walk-forward optimization, and
    feature storage workflows.
    """

    def OptimizeParameters(self, request, context):
        """Walk-forward parameter optimization streaming progress updates to callers."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AnalyzeWalkForward(self, request, context):
        """Run statistical analysis across walk-forward windows."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PredictSignal(self, request, context):
        """Generate a single ML signal prediction."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PredictSignalsBatch(self, request, context):
        """Stream batch ML predictions for multiple feature vectors."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StoreFeatures(self, request, context):
        """Store computed features inside the feature store."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Report service health state."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AnalyzeMLBacktestPerformance(self, request, context):
        """Analyze ML-driven backtest performance submitted by backtest service."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListModels(self, request, context):
        """============================================================
        GenAI Service Integration RPCs
        ============================================================

        List all ML models owned by the user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetModelInfo(self, request, context):
        """Get detailed information about a specific ML model."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RecommendModel(self, request, context):
        """Recommend ML models based on strategy type and market regime."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SuggestParameters(self, request, context):
        """Suggest optimal strategy parameters using Bayesian optimization."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetMLBacktestPerformance(self, request, context):
        """Get stored ML backtest performance analysis results."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SendDriftNotification(self, request, context):
        """Send drift detection notification to GenAI service."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "OptimizeParameters": grpc.unary_stream_rpc_method_handler(
            servicer.OptimizeParameters,
            request_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.OptimizeRequest.FromString,
            response_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.OptimizeProgress.SerializeToString,
        ),
        "AnalyzeWalkForward": grpc.unary_unary_rpc_method_handler(
            servicer.AnalyzeWalkForward,
            request_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeRequest.FromString,
            response_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeResponse.SerializeToString,
        ),
        "PredictSignal": grpc.unary_unary_rpc_method_handler(
            servicer.PredictSignal,
            request_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.MLPredictionRequest.FromString,
            response_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.MLSignalInsight.SerializeToString,
        ),
        "PredictSignalsBatch": grpc.unary_stream_rpc_method_handler(
            servicer.PredictSignalsBatch,
            request_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.BatchMLPredictionRequest.FromString,
            response_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.MLSignalInsight.SerializeToString,
        ),
        "StoreFeatures": grpc.unary_unary_rpc_method_handler(
            servicer.StoreFeatures,
            request_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.FeatureStoreRequest.FromString,
            response_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.FeatureStoreResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.HealthCheckRequest.FromString,
            response_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.HealthCheckResponse.SerializeToString,
        ),
        "AnalyzeMLBacktestPerformance": grpc.unary_unary_rpc_method_handler(
            servicer.AnalyzeMLBacktestPerformance,
            request_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeMLBacktestPerformanceRequest.FromString,
            response_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeMLBacktestPerformanceResponse.SerializeToString,
        ),
        "ListModels": grpc.unary_unary_rpc_method_handler(
            servicer.ListModels,
            request_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.ListModelsRequest.FromString,
            response_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.ListModelsResponse.SerializeToString,
        ),
        "GetModelInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetModelInfo,
            request_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.GetModelInfoRequest.FromString,
            response_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.GetModelInfoResponse.SerializeToString,
        ),
        "RecommendModel": grpc.unary_unary_rpc_method_handler(
            servicer.RecommendModel,
            request_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.RecommendModelRequest.FromString,
            response_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.RecommendModelResponse.SerializeToString,
        ),
        "SuggestParameters": grpc.unary_unary_rpc_method_handler(
            servicer.SuggestParameters,
            request_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.SuggestParametersRequest.FromString,
            response_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.SuggestParametersResponse.SerializeToString,
        ),
        "GetMLBacktestPerformance": grpc.unary_unary_rpc_method_handler(
            servicer.GetMLBacktestPerformance,
            request_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.GetMLBacktestPerformanceRequest.FromString,
            response_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.GetMLBacktestPerformanceResponse.SerializeToString,
        ),
        "SendDriftNotification": grpc.unary_unary_rpc_method_handler(
            servicer.SendDriftNotification,
            request_deserializer=services_dot_ml_dot_v1_dot_ml__service__pb2.DriftNotificationRequest.FromString,
            response_serializer=services_dot_ml_dot_v1_dot_ml__service__pb2.DriftNotificationResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ml.MLService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("ml.MLService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class MLService(object):
    """ML Service - gRPC API used for ML prediction, walk-forward optimization, and
    feature storage workflows.
    """

    @staticmethod
    def OptimizeParameters(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/ml.MLService/OptimizeParameters",
            services_dot_ml_dot_v1_dot_ml__service__pb2.OptimizeRequest.SerializeToString,
            services_dot_ml_dot_v1_dot_ml__service__pb2.OptimizeProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AnalyzeWalkForward(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml.MLService/AnalyzeWalkForward",
            services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeRequest.SerializeToString,
            services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def PredictSignal(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml.MLService/PredictSignal",
            services_dot_ml_dot_v1_dot_ml__service__pb2.MLPredictionRequest.SerializeToString,
            services_dot_ml_dot_v1_dot_ml__service__pb2.MLSignalInsight.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def PredictSignalsBatch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/ml.MLService/PredictSignalsBatch",
            services_dot_ml_dot_v1_dot_ml__service__pb2.BatchMLPredictionRequest.SerializeToString,
            services_dot_ml_dot_v1_dot_ml__service__pb2.MLSignalInsight.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StoreFeatures(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml.MLService/StoreFeatures",
            services_dot_ml_dot_v1_dot_ml__service__pb2.FeatureStoreRequest.SerializeToString,
            services_dot_ml_dot_v1_dot_ml__service__pb2.FeatureStoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml.MLService/HealthCheck",
            services_dot_ml_dot_v1_dot_ml__service__pb2.HealthCheckRequest.SerializeToString,
            services_dot_ml_dot_v1_dot_ml__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AnalyzeMLBacktestPerformance(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml.MLService/AnalyzeMLBacktestPerformance",
            services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeMLBacktestPerformanceRequest.SerializeToString,
            services_dot_ml_dot_v1_dot_ml__service__pb2.AnalyzeMLBacktestPerformanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListModels(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml.MLService/ListModels",
            services_dot_ml_dot_v1_dot_ml__service__pb2.ListModelsRequest.SerializeToString,
            services_dot_ml_dot_v1_dot_ml__service__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetModelInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml.MLService/GetModelInfo",
            services_dot_ml_dot_v1_dot_ml__service__pb2.GetModelInfoRequest.SerializeToString,
            services_dot_ml_dot_v1_dot_ml__service__pb2.GetModelInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RecommendModel(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml.MLService/RecommendModel",
            services_dot_ml_dot_v1_dot_ml__service__pb2.RecommendModelRequest.SerializeToString,
            services_dot_ml_dot_v1_dot_ml__service__pb2.RecommendModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SuggestParameters(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml.MLService/SuggestParameters",
            services_dot_ml_dot_v1_dot_ml__service__pb2.SuggestParametersRequest.SerializeToString,
            services_dot_ml_dot_v1_dot_ml__service__pb2.SuggestParametersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetMLBacktestPerformance(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml.MLService/GetMLBacktestPerformance",
            services_dot_ml_dot_v1_dot_ml__service__pb2.GetMLBacktestPerformanceRequest.SerializeToString,
            services_dot_ml_dot_v1_dot_ml__service__pb2.GetMLBacktestPerformanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SendDriftNotification(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml.MLService/SendDriftNotification",
            services_dot_ml_dot_v1_dot_ml__service__pb2.DriftNotificationRequest.SerializeToString,
            services_dot_ml_dot_v1_dot_ml__service__pb2.DriftNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
