# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from mysingle.protos.services.subscription.v1 import (
    subscription_service_pb2 as services_dot_subscription_dot_v1_dot_subscription__service__pb2,
)

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in services/subscription/v1/subscription_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SubscriptionServiceStub(object):
    """Subscription Service - gRPC API
    Used for quota checking, subscription management, and entitlement verification
    Port: 50052
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckResourceQuota = channel.unary_unary(
            "/subscription.v1.SubscriptionService/CheckResourceQuota",
            request_serializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.CheckResourceQuotaRequest.SerializeToString,
            response_deserializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.CheckResourceQuotaResponse.FromString,
            _registered_method=True,
        )
        self.CheckFeatureAccess = channel.unary_unary(
            "/subscription.v1.SubscriptionService/CheckFeatureAccess",
            request_serializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.CheckFeatureAccessRequest.SerializeToString,
            response_deserializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.CheckFeatureAccessResponse.FromString,
            _registered_method=True,
        )
        self.GetSubscription = channel.unary_unary(
            "/subscription.v1.SubscriptionService/GetSubscription",
            request_serializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetSubscriptionRequest.SerializeToString,
            response_deserializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetSubscriptionResponse.FromString,
            _registered_method=True,
        )
        self.GetEntitlements = channel.unary_unary(
            "/subscription.v1.SubscriptionService/GetEntitlements",
            request_serializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetEntitlementsRequest.SerializeToString,
            response_deserializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetEntitlementsResponse.FromString,
            _registered_method=True,
        )
        self.GetUsage = channel.unary_unary(
            "/subscription.v1.SubscriptionService/GetUsage",
            request_serializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetUsageRequest.SerializeToString,
            response_deserializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetUsageResponse.FromString,
            _registered_method=True,
        )
        self.GetAllQuotas = channel.unary_unary(
            "/subscription.v1.SubscriptionService/GetAllQuotas",
            request_serializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetAllQuotasRequest.SerializeToString,
            response_deserializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetAllQuotasResponse.FromString,
            _registered_method=True,
        )
        self.CheckQuota = channel.unary_unary(
            "/subscription.v1.SubscriptionService/CheckQuota",
            request_serializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.CheckQuotaRequest.SerializeToString,
            response_deserializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.CheckQuotaResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/subscription.v1.SubscriptionService/HealthCheck",
            request_serializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )


class SubscriptionServiceServicer(object):
    """Subscription Service - gRPC API
    Used for quota checking, subscription management, and entitlement verification
    Port: 50052
    """

    def CheckResourceQuota(self, request, context):
        """Check if user can create more resources (strategies, templates, etc.)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CheckFeatureAccess(self, request, context):
        """Check feature access (e.g., private_templates)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSubscription(self, request, context):
        """Get user's subscription details"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetEntitlements(self, request, context):
        """Get user's entitlements (features and limits)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUsage(self, request, context):
        """Get current usage for a specific metric (legacy: backtests, API calls, etc.)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetAllQuotas(self, request, context):
        """Get all quota statuses for a user (legacy)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CheckQuota(self, request, context):
        """Check if user can perform action within quota (legacy)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SubscriptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CheckResourceQuota": grpc.unary_unary_rpc_method_handler(
            servicer.CheckResourceQuota,
            request_deserializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.CheckResourceQuotaRequest.FromString,
            response_serializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.CheckResourceQuotaResponse.SerializeToString,
        ),
        "CheckFeatureAccess": grpc.unary_unary_rpc_method_handler(
            servicer.CheckFeatureAccess,
            request_deserializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.CheckFeatureAccessRequest.FromString,
            response_serializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.CheckFeatureAccessResponse.SerializeToString,
        ),
        "GetSubscription": grpc.unary_unary_rpc_method_handler(
            servicer.GetSubscription,
            request_deserializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetSubscriptionRequest.FromString,
            response_serializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetSubscriptionResponse.SerializeToString,
        ),
        "GetEntitlements": grpc.unary_unary_rpc_method_handler(
            servicer.GetEntitlements,
            request_deserializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetEntitlementsRequest.FromString,
            response_serializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetEntitlementsResponse.SerializeToString,
        ),
        "GetUsage": grpc.unary_unary_rpc_method_handler(
            servicer.GetUsage,
            request_deserializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetUsageRequest.FromString,
            response_serializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetUsageResponse.SerializeToString,
        ),
        "GetAllQuotas": grpc.unary_unary_rpc_method_handler(
            servicer.GetAllQuotas,
            request_deserializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetAllQuotasRequest.FromString,
            response_serializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetAllQuotasResponse.SerializeToString,
        ),
        "CheckQuota": grpc.unary_unary_rpc_method_handler(
            servicer.CheckQuota,
            request_deserializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.CheckQuotaRequest.FromString,
            response_serializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.CheckQuotaResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.HealthCheckRequest.FromString,
            response_serializer=services_dot_subscription_dot_v1_dot_subscription__service__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "subscription.v1.SubscriptionService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "subscription.v1.SubscriptionService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class SubscriptionService(object):
    """Subscription Service - gRPC API
    Used for quota checking, subscription management, and entitlement verification
    Port: 50052
    """

    @staticmethod
    def CheckResourceQuota(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/subscription.v1.SubscriptionService/CheckResourceQuota",
            services_dot_subscription_dot_v1_dot_subscription__service__pb2.CheckResourceQuotaRequest.SerializeToString,
            services_dot_subscription_dot_v1_dot_subscription__service__pb2.CheckResourceQuotaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CheckFeatureAccess(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/subscription.v1.SubscriptionService/CheckFeatureAccess",
            services_dot_subscription_dot_v1_dot_subscription__service__pb2.CheckFeatureAccessRequest.SerializeToString,
            services_dot_subscription_dot_v1_dot_subscription__service__pb2.CheckFeatureAccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetSubscription(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/subscription.v1.SubscriptionService/GetSubscription",
            services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetSubscriptionRequest.SerializeToString,
            services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetSubscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetEntitlements(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/subscription.v1.SubscriptionService/GetEntitlements",
            services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetEntitlementsRequest.SerializeToString,
            services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetEntitlementsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetUsage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/subscription.v1.SubscriptionService/GetUsage",
            services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetUsageRequest.SerializeToString,
            services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetAllQuotas(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/subscription.v1.SubscriptionService/GetAllQuotas",
            services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetAllQuotasRequest.SerializeToString,
            services_dot_subscription_dot_v1_dot_subscription__service__pb2.GetAllQuotasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CheckQuota(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/subscription.v1.SubscriptionService/CheckQuota",
            services_dot_subscription_dot_v1_dot_subscription__service__pb2.CheckQuotaRequest.SerializeToString,
            services_dot_subscription_dot_v1_dot_subscription__service__pb2.CheckQuotaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/subscription.v1.SubscriptionService/HealthCheck",
            services_dot_subscription_dot_v1_dot_subscription__service__pb2.HealthCheckRequest.SerializeToString,
            services_dot_subscription_dot_v1_dot_subscription__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
